# This is the configuration used to check the `Bitaculous::Assetify` source code.
#
# See <https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml> for more details.

# === Vendor ===

require: rubocop-rspec

# === Overrides ===

AllCops:
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Description: 'Gems should be alphabetically sorted within groups.'
  Enabled: false

Gemspec/OrderedDependencies:
  Description: 'Dependencies in the gemspec should be alphabetically sorted.'
  Enabled: false

Layout/AlignHash:
  Description: 'Align the elements of a hash literal if they span more than one line.'
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: table

Layout/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: false

Layout/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Exclude:
    - Guardfile

Lint/ScriptPermission:
  Description: 'Grant script file execute permission.'
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Description: 'Limit lines to 120 characters with 10 characters as buffer.'
  Max: 130

Style/AsciiComments:
  Description: 'Use only ASCII symbols in comments.'
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Description: 'Checks if there is an empty line after example group blocks.'
  Enabled: false

RSpec/MultipleExpectations:
  Description: 'Checks if examples contain too many `expect` calls.'
  Enabled: true
  Max: 4
