addons:
  code_climate:
    repo_token: 9ba16536b271f2b04959d793df1fdf0cafd090966bc3967105e2c049b1e1d485

branches:
  except:
    - gh-pages

cache: bundler

env:
  - COVERAGE=true

language: ruby

notifications:
  email:
    - dev@bitaculous.com

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
