addons:
  code_climate:
    repo_token: 9ba16536b271f2b04959d793df1fdf0cafd090966bc3967105e2c049b1e1d485
branches:
  except:
    - gh-pages
cache: bundler
env:
  - COVERAGE=true
language: ruby
notifications:
  email:
    - dev@bitaculous.com
rvm:
  - 2.2.4
  - 2.3.0
sudo: false